### ISSUE TITLE
Get command output response in JSON format

### ISSUE THREAD

**Issue by mohsinrazasfdc** [axlemax/sfdx#7]
HI - How can I get the response/result for any command in JSON format? Something like this.

sfdx.list().then(function(response){
	//response as JSON string
});

**Comment by axlemax** [comment]
Hi -

Commands return JSON-formated output when the 'json' flag is set to 'true'.

`sfdx.list({ json: true })`

See more info at the API documentation [here](https://github.com/axlemax/sfdx/blob/master/docs/api.md). I'll try to add examples that are more explicit soon.

If you are interested, I am also developing a project that uses JSON output from this module in my SFDX-WebUI project [here](https://github.com/axlemax/sfdx-webui).

**Comment by mohsinrazasfdc** [comment]
Thanks Zander. Are you still actively developing this one as well? I have added few more methods for some missing SFDX commands which I wanted to submit to this project.

**Comment by axlemax** [comment]
Yeah! It's a bit of a side project, but I am working with it / on it actively, so feel free to submit a pull request or any other questions you might have.
